//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zsw.TestDB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentClass
    {
        public string ClassName { get; set; }
        public int ClassGrade { get; set; }
        public string StudentName { get; set; }
        public int Age { get; set; }
        public int StudentGrade { get; set; }
    }
}
